global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        
  - job_name: 'web'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5000']
        
  - job_name: 'server'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8081']